/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-26 07:14:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Login to cognifront</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/loginpage.css\">\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<input type=\"hidden\" id=\"status\" value=\"");
      out.print(request.getAttribute("status"));
      out.write("\">\r\n");
      out.write("<!--Header  -->\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <a href=\"index.jsp\">Home</a>\r\n");
      out.write("        <a href=\"#\">About</a>\r\n");
      out.write("        <a href=\"#\">Services</a>\r\n");
      out.write("        <a href=\"#\">Contact</a>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <form action=\"#\" class=\"search-bar\">\r\n");
      out.write("        <input type=\"text\" placeholder=\"search...\">\r\n");
      out.write("        <button class=\"search\"><i class='bx bx-search-alt-2'></i></button>\r\n");
      out.write("    </form>\r\n");
      out.write("   </header>  \r\n");
      out.write("<!--Main Container  -->\r\n");
      out.write("     <div class=\"container d-flex justify-content-center align-items-center min-vh-70\">\r\n");
      out.write("    <!--Login Container-->\r\n");
      out.write("       <div class=\"row border rounded-5 p-3 bg-lightblue  box-area\">\r\n");
      out.write("    <!--Left Box-->\r\n");
      out.write("  <div class=\"col-md-6 rounded-4 d-flex justify-content-center align-items-center flex-column left-box\" style=\"background-image: linear-gradient(-135deg,lightcoral,rgb(241, 49, 49));\">\r\n");
      out.write("                  <p class=\"text-white fs-1\" style=\"font-family: 'Courier New', Courier, monospace; font-weight: 600;\">Cognifront</p>\r\n");
      out.write("           <div class=\"featured-image mb-3\">\r\n");
      out.write("            <img src=\"images/undraw_data_reports_706v-removebg-preview.png\" class=\"img-fluid\" style=\"width: 350px;\">\r\n");
      out.write("           </div>\r\n");
      out.write("           <p class=\"text-white fs-2\" style=\"font-family: 'Courier New', Courier, monospace; font-weight: 600;\">Sign in</p>\r\n");
      out.write("           <small class=\"text-white text-wrap text-center\" style=\"width: 17rem;font-family: 'Courier New', Courier, monospace;\">Manage Business Query With Ease</small>\r\n");
      out.write("       </div> \r\n");
      out.write(" <!-- Right Box-->\r\n");
      out.write("       <div class=\"col-md-6 right-box\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("                <div class=\"header-text mb-4\">\r\n");
      out.write("                     <h2>Hello,Again</h2>\r\n");
      out.write("                     <p>We are happy to have you back.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <form action=\"Login\" method=\"post\">\r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control-lg bg-light fs-6\" placeholder=\"Username\" name=\"username\" id=\"username\" required=\"required\" >\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control-lg bg-light fs-6\" placeholder=\"Email address\" name=\"email\" id=\"email\" required=\"required\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group mb-1\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control form-control-lg bg-light fs-6\" placeholder=\"Password\" name=\"password\"  id=\"password\" required=\"required\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group mb-5 d-flex justify-content-between\">\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input type=\"checkbox\" class=\"form-check-input\" id=\"formCheck\">\r\n");
      out.write("                        <label for=\"formCheck\" class=\"form-check-label text-secondary\"><small>Remember Me</small></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"forgot\">\r\n");
      out.write("                        <small><a href=\"#\">Forgot Password?</a></small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("                <input class=\"btn btn-success w-100 fs-6 py-2\" type=\"submit\" value=\"Login\">\r\n");
      out.write("                </div>\r\n");
      out.write("                 </form>\r\n");
      out.write("                <div class=\"input-group mb-3 \">\r\n");
      out.write("                    <button class=\"btn btn-lg btn-light w-100 fs-6\" ><img src=\"images/google.png\" style=\"width:20px\" class=\"me-2\"><small>Sign In with Google</small></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <small>Don't have account? <a href=\"registration.jsp\">Create one</a></small>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("       </div> \r\n");
      out.write("    </div>\r\n");
      out.write("          </div>\r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("         <footer class=\"footer\">\r\n");
      out.write("           <div class=\"social-media\">\r\n");
      out.write("            <a href=\"\"><i class='bx bxl-gmail'></i></a>\r\n");
      out.write("            <a href=\"https://www.linkedin.com/in/uday-sharma-602b33267\"><i class='bx bxl-linkedin'></i></a>\r\n");
      out.write("            <a href=\"\"><i class='bx bxl-instagram'></i></a>\r\n");
      out.write("            <a href=\"\"><i class='bx bxl-github' ></i></a>\r\n");
      out.write("        </div></footer>\r\n");
      out.write("  <!-- Scripts -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"js/main.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"alert/dist/sweetalert.css\">\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	var status=document.getElementById(\"status\").value;\r\n");
      out.write("	if(status==\"failed\"){\r\n");
      out.write("		swal(\"Sorry\",\"Wrong Username or Email or Password\",\"error\");\r\n");
      out.write("	}\r\n");
      out.write("	else if(status==\"InvalidUname\"){\r\n");
      out.write("		swal(\"Sorry\",\"Please Enter Correct Username\",\"error\");\r\n");
      out.write("	}\r\n");
      out.write("	else if(status==\"InvalidUemail\"){\r\n");
      out.write("		swal(\"Sorry\",\"Please Enter Correct Email\",\"error\");\r\n");
      out.write("	}\r\n");
      out.write("	else if(status==\"InvalidUpassword\"){\r\n");
      out.write("		swal(\"Sorry\",\"Please Enter Correct Password\",\"error\");\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
